# Generated by Django 4.1.7 on 2023-03-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioucn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='IdReserva',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
