# Generated by Django 4.1.7 on 2023-03-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioucn', '0003_delete_person_alter_equipos_idequipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soportes',
            name='TipoSoporte',
        ),
        migrations.AddField(
            model_name='soportes',
            name='Detalle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
